import type { Metadata } from "next";
import Link from "next/link";
import { cookies } from "next/headers";
import {
  languageCookieName,
  normalizeLanguage,
  type AppLanguage,
} from "@/lib/i18n";
import { siteDescription, siteName, siteTitle } from "@/lib/site";

export const metadata: Metadata = {
  title: "About SmartRecipe",
  description:
    "Learn what SmartRecipe does, how AI and recipe photos are used, and where to find support and privacy information.",
  alternates: {
    canonical: "/about",
  },
};

const appVersion = "1.0";

const aboutCopy: Record<
  AppLanguage,
  {
    title: string;
    intro: string;
    versionLabel: string;
    back: string;
    support: string;
    privacy: string;
    terms: string;
    sections: { title: string; text: string }[];
  }
> = {
  pl: {
    title: "O aplikacji",
    intro:
      "SmartRecipe pomaga gotować z produktów, które już masz w domu. Aplikacja generuje przepisy, listy zakupów, plan posiłków i pomaga ograniczać marnowanie jedzenia.",
    versionLabel: "Wersja aplikacji",
    back: "← Wróć do aplikacji",
    support: "Pomoc",
    privacy: "Prywatność",
    terms: "Regulamin",
    sections: [
      {
        title: "Czym jest SmartRecipe?",
        text: "To asystent gotowania, który łączy Twoją spiżarnię, preferencje, budżet i czas w jeden prosty generator przepisów.",
      },
      {
        title: "AI i przepisy",
        text: "Przepisy są generowane przez AI na podstawie składników i preferencji. Zawsze sprawdzaj alergeny, świeżość produktów oraz bezpieczeństwo przygotowania.",
      },
      {
        title: "Zdjęcia dań",
        text: "Zdjęcia przepisów mogą pochodzić z Pexels i są dobierane tak, aby możliwie dobrze pasować do nazwy dania.",
      },
      {
        title: "Prywatność",
        text: "Aplikacja przechowuje dane potrzebne do działania konta, zapisanych przepisów, historii, list zakupów, spiżarni i planera.",
      },
    ],
  },
  en: {
    title: "About the app",
    intro:
      "SmartRecipe helps you cook with ingredients you already have at home. It generates recipes, shopping lists, meal plans and helps reduce food waste.",
    versionLabel: "App version",
    back: "← Back to app",
    support: "Support",
    privacy: "Privacy",
    terms: "Terms",
    sections: [
      {
        title: "What is SmartRecipe?",
        text: "It is a cooking assistant that combines your pantry, preferences, budget and time into one simple recipe generator.",
      },
      {
        title: "AI and recipes",
        text: "Recipes are generated by AI from your ingredients and preferences. Always check allergens, product freshness and safe food preparation.",
      },
      {
        title: "Dish photos",
        text: "Recipe photos may be provided by Pexels and are selected to match the dish name as closely as possible.",
      },
      {
        title: "Privacy",
        text: "The app stores data needed for accounts, saved recipes, history, shopping lists, pantry tracking and meal planning.",
      },
    ],
  },
  uk: {
    title: "Про застосунок",
    intro:
      "SmartRecipe допомагає готувати з продуктів, які вже є вдома. Застосунок генерує рецепти, списки покупок, плани страв і допомагає менше марнувати їжу.",
    versionLabel: "Версія застосунку",
    back: "← Назад до застосунку",
    support: "Підтримка",
    privacy: "Приватність",
    terms: "Умови",
    sections: [
      {
        title: "Що таке SmartRecipe?",
        text: "Це кулінарний асистент, який поєднує твою комору, вподобання, бюджет і час в один простий генератор рецептів.",
      },
      {
        title: "AI і рецепти",
        text: "Рецепти генеруються AI на основі інгредієнтів і вподобань. Завжди перевіряй алергени, свіжість продуктів і безпечне приготування.",
      },
      {
        title: "Фото страв",
        text: "Фото рецептів можуть надходити з Pexels і підбираються так, щоб якомога краще відповідати назві страви.",
      },
      {
        title: "Приватність",
        text: "Застосунок зберігає дані, потрібні для акаунта, збережених рецептів, історії, списків покупок, комори й планування страв.",
      },
    ],
  },
};

export default async function AboutPage() {
  const language = normalizeLanguage(
    (await cookies()).get(languageCookieName)?.value,
  );
  const copy = aboutCopy[language];

  return (
    <main className="app-shell subpage-shell bg-[#f7f4ed] px-4 py-6 text-[#25322b] sm:px-8 sm:py-10">
      <article className="mx-auto max-w-3xl rounded-[2rem] border border-[#e2dfd6] bg-[#fffdf8] p-5 shadow-sm sm:p-8">
        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#fc5726]">
          {siteName}
        </p>
        <h1 className="mt-2 font-serif text-4xl font-semibold">
          {copy.title}
        </h1>
        <p className="mt-2 text-sm font-semibold text-[#68736b]">
          {siteTitle}
        </p>
        <p className="mt-5 leading-7 text-[#59675f]">{copy.intro}</p>

        <section className="mt-7 rounded-[1.5rem] border border-[#d6e2d8] bg-[#eef6ef] p-4 sm:p-5">
          <p className="text-xs font-bold uppercase tracking-[0.16em] text-[#365a46]">
            {copy.versionLabel}
          </p>
          <p className="mt-2 font-serif text-3xl font-semibold text-[#025026]">
            {appVersion}
          </p>
          <p className="mt-2 text-sm leading-6 text-[#68736b]">
            {siteDescription}
          </p>
        </section>

        <div className="mt-7 grid gap-4 sm:grid-cols-2">
          {copy.sections.map((section) => (
            <section
              key={section.title}
              className="rounded-[1.5rem] border border-[#e2dfd6] bg-white p-4 sm:p-5"
            >
              <h2 className="font-serif text-2xl font-semibold">
                {section.title}
              </h2>
              <p className="mt-2 text-sm leading-6 text-[#59675f]">
                {section.text}
              </p>
            </section>
          ))}
        </div>

        <div className="mt-7 flex flex-wrap gap-3">
          <Link
            href="/support"
            className="inline-flex h-11 items-center justify-center rounded-xl bg-[#025026] px-4 text-sm font-semibold text-white"
          >
            {copy.support}
          </Link>
          <Link
            href="/privacy"
            className="inline-flex h-11 items-center justify-center rounded-xl border border-[#d8d7d0] bg-white px-4 text-sm font-semibold text-[#25322b]"
          >
            {copy.privacy}
          </Link>
          <Link
            href="/terms"
            className="inline-flex h-11 items-center justify-center rounded-xl border border-[#d8d7d0] bg-white px-4 text-sm font-semibold text-[#25322b]"
          >
            {copy.terms}
          </Link>
          <Link
            href="/"
            className="inline-flex h-11 items-center justify-center rounded-xl border border-[#d8d7d0] bg-white px-4 text-sm font-semibold text-[#25322b]"
          >
            {copy.back}
          </Link>
        </div>
      </article>
    </main>
  );
}
